import { mkdir, writeFile } from 'node:fs/promises';
import { slides as week01 } from '../src/week01.mjs';
import { slides as week02 } from '../src/week02.mjs';
const lessons = [{week:'01', slides:week01, title:'Mobile Applications and the Development Landscape', label:'MOBILE APPLICATIONS'}, {week:'02', slides:week02, title:'Framework Control Flow and Declarative UI', label:'FRAMEWORK CONTROL FLOW'}];
for (const {week,slides,title,label} of lessons) {
const escape = s => s.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const sections = slides.map((s,i)=>`<section id="${s.id}" class="${s.kind||''}" aria-labelledby="title-${s.id}" data-time="${s.time}"><div class="slide-inner"><p class="eyebrow">${s.chapter} <span class="section-count">${String(i+1).padStart(2,'0')} / ${slides.length}</span></p><h2 id="title-${s.id}" tabindex="-1">${s.title}</h2>${s.body}${s.source?`<p class="sources">Read further: ${s.source}</p>`:''}</div></section>`).join('\n');
const toc = slides.map((s,i)=>`<li><a href="#/${s.id}">${String(i+1).padStart(2,'0')} · ${s.title}</a></li>`).join('');
const shell = reading => `<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="description" content="Week ${week}: ${title}. Interactive CS 311 lecture."><title>Week ${week} · ${title} · CS 311</title><link rel="icon" href="../../mark.svg"><link rel="stylesheet" href="/src/style.css"></head>
<body class="${reading?'reading':'deck'}"><a class="skip" href="#main">Skip to lesson</a><header class="toolbar"><a class="brand" href="../../index.html">204311 <span>/ SWIFT</span></a><span class="lesson-label">W${week} · ${label}</span><nav aria-label="Lesson tools"><button id="overview" type="button">Overview</button><a href="${reading?'index.html':'reading.html'}" id="mode-link">${reading?'Slides':'Read'}</a><a href="../../downloads/week-${week}-offline.zip" download>Offline ↓</a></nav></header>
<main id="main" class="reveal" tabindex="-1"><h1 class="sr-only">Week ${week} ${title}</h1><div class="slides">${sections}</div></main>
<footer class="navigation"><span id="chapter-label">Week ${week}</span><span id="position" role="status" aria-live="polite">1 / ${slides.length}</span><div><button id="previous" type="button" aria-label="Previous slide">← Previous</button><button id="next" type="button" aria-label="Next slide">Next →</button></div></footer><div class="course-progress" aria-hidden="true"><i></i></div>
<dialog id="contents" aria-labelledby="contents-title"><div class="dialog-heading"><h2 id="contents-title">Week ${week} overview</h2><button id="close-overview" type="button">Close</button></div><p>Use ← → or Previous / Next to reveal points, then change slides. Read shows all content together at a comfortable text size.</p><ol>${toc}</ol></dialog>
<noscript><p class="no-script">Reading mode is available without JavaScript. All core explanations and examples are below; prediction answers open with their disclosure controls.</p></noscript><script type="module" src="/src/main.js"></script></body></html>`;
await mkdir(`2027/week-${week}`,{recursive:true});
await writeFile(`2027/week-${week}/index.html`,shell(false));
await writeFile(`2027/week-${week}/reading.html`,shell(true));
console.log(`Generated Week ${week}: ${slides.length} slides, ${slides.reduce((n,s)=>n+s.time,0)} minutes.`);
}
await writeFile('index.html',`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CS 311 · Swift lectures</title><link rel="icon" href="./mark.svg"><link rel="stylesheet" href="/src/style.css"></head><body class="home"><header class="toolbar"><span class="brand">204311 <span>/ SWIFT</span></span><span>2027 COURSE EDITION</span></header><main><p class="eyebrow">CS 311 · MOBILE APPLICATION DEVELOPMENT FRAMEWORKS</p><h1>From a useful idea<br>to a mobile app.</h1><p class="lead">Explore mobile development with Swift and SwiftUI.<br>Short explanations. Decisions to discuss. Code to reason about.</p><a class="lesson-card" href="./2027/week-01/"><span class="week-number">01</span><div><p class="eyebrow">120 MINUTES · LECTURE</p><h2>Mobile applications and<br>the development landscape</h2><p>Context → frameworks → the Apple stack → your choices</p></div><span aria-hidden="true">↗</span></a><div class="home-links"><a href="./2027/week-01/reading.html">Read the lesson</a><a href="./downloads/week-01-practice.zip" download>Practice source ↓</a><a href="./downloads/week-01-offline.zip" download>Offline package ↓</a></div><a class="lesson-card" href="./2027/week-02/"><span class="week-number">02</span><div><p class="eyebrow">120 MINUTES · LECTURE</p><h2>Framework control flow<br>and declarative UI</h2><p>Events → state → views → ownership</p></div><span aria-hidden="true">↗</span></a><div class="home-links"><a href="./2027/week-02/reading.html">Read Week 02</a><a href="./downloads/week-02-practice.zip" download>Week 02 practice ↓</a><a href="./downloads/week-02-offline.zip" download>Week 02 offline ↓</a></div><p class="small">English lecture content · Xcode on Mac / Swift Playgrounds on iPad<br>No login, response collection or analytics.</p></main><footer>CS 311 · 204311 &nbsp; / &nbsp; Campus Life, But Smarter</footer></body></html>`);
