// W01-Lecture | 120 minutes | OBE: mobile characteristics 1h; framework evolution 1h.
// CLO 1 primary; CLO 2 and 5 supporting. Prerequisite: basic programming; no Swift required.
// Tools: browser for class; Xcode/Mac or Swift Playgrounds/iPad for optional practice.
// Narrative revision: 2026-10-06. SwiftUI overview rechecked; other retained sources: 2026-09-13. Hardware and Swift compilation verification remain pending.
// Original teaching examples. Public formative explanations only; no assessment answers.
const link = (label, url) => `<a href="${url}">${label}</a>`;
const apple = 'https://developer.apple.com/';
const privacy = link('Apple · Privacy', apple+'design/human-interface-guidelines/privacy');
const access = link('Apple · Accessibility', apple+'design/human-interface-guidelines/accessibility');
const ui = link('Apple · SwiftUI', apple+'swiftui/');
const swift = link('Apple · Swift Pathway', apple+'swift/get-started/');
const tools = link('Apple · Tools and distribution', apple+'documentation/technologyoverviews/tools-and-distribution');
const web = link('web.dev · PWA capabilities','https://web.dev/learn/pwa/capabilities');
const react = link('React Native · Overview','https://reactnative.dev/');
const esc = s => s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const code = s => `<pre><code>${esc(s)}</code></pre>`;
const cards = items => `<div class="cards">${items.map(([a,b])=>`<article class="card"><h3>${a}</h3><p>${b}</p></article>`).join('')}</div>`;
const prompt = s => `<p class="prompt"><span>Think it through</span>${s}</p>`;
const reveal = (label, s) => `<details><summary>${label}</summary><div class="answer">${s}</div></details>`;
const steps = arr => `<ol class="steps">${arr.map(x=>`<li>${x}</li>`).join('')}</ol>`;
const phone = `<div class="phone" role="img" aria-label="Illustrative shuttle screen. North Gate route, estimated arrival 4 minutes, last updated 2 minutes ago. This is sample data."><div class="phone-bar">08:05 <span>17% battery</span></div><p class="eyebrow">CAMPUS SHUTTLE</p><div class="route-line"><i></i><i></i><i></i><i></i></div><h3>North Gate</h3><p class="arrival">4 <span>min</span></p><p class="status">Updated 2 min ago</p><p class="phone-bottom">Is this estimate still reliable?</p></div>`;
export const slides = [
{id:'welcome',title:"Can Mali trust the next shuttle?",time:2,chapter:"Prologue",kind:'hero',body:`<div class="split"><div><p class="lead">Mobile applications and the development landscape</p><p>What changes when software travels with its user?</p><p class="meta">CS 311 · 204311<br>120 minutes · Basic programming assumed<br>No prior Swift required</p></div>${phone}</div>`},
{id:'agenda',title:"One journey. Six problems to solve.",time:3,chapter:"Prologue",body:cards([['1–3 · Help Mali choose','An old estimate, an interrupted task, a denied permission.'],['4–5 · Build the repair','From printed text to a screen; from one screen to many states.'],['6 · Bring it to campus','Choose how different people will reach the service.']])+`<p class="lead">First solve the problem. Then name the idea behind it.</p><p class="small">By the end: classify conditions · explain framework evolution · distinguish tool roles · recommend delivery.<br>CLO 1: principles and evolution · CLO 2: development reasoning · CLO 5: responsible design</p>`},
{id:'shuttle',title:"Seven minutes. Can she trust “4 min”?",time:4,chapter:"1 / The estimate freezes",body:`<div class="split"><div><p class="lead">Mali is heading to the shuttle stop.</p><ul><li>Rain. One hand holds an umbrella.</li><li>Battery: 17%. Campus Wi-Fi: weak.</li><li>The shuttle position is two minutes old.</li></ul>${prompt('What must this app do well in the next ten seconds?')}<p class="small">Think individually → compare with a partner → share one priority.</p></div>${phone}</div>`},
{id:'failure',title:"The connection drops. What stays on screen?",time:6,chapter:"1 / Try a repair",body:`<div class="split"><div><p>Mali’s estimate stops updating. Predict a useful screen, then try each state.</p><label for="arrival-state">Arrival state</label><select id="arrival-state"><option>Loading</option><option>Current</option><option>Stale</option><option>Unavailable</option><option>Retrying</option></select><button type="button" data-reset>Reset</button><p class="small">Local interface model; no network request is made.</p></div><div class="card live-card" aria-live="polite"><p class="eyebrow">NORTH GATE</p><h3 id="arrival-title">Checking arrivals…</h3><p id="arrival-message">Route information stays visible while we wait.</p></div></div><p class="takeaway">Offline behavior should be useful and honest.</p><noscript><p>Current: show a fresh estimate. Stale: show its age. Unavailable: explain what still works. Retrying: acknowledge progress.</p></noscript>`},
{id:'context',title:"Theory: mobile context creates requirements",time:4,chapter:"1 / Name what happened",body:`<p class="lead">Mobile software serves a person whose conditions can change during a task.</p>${steps(['Person','Device','Environment','Platform'])}<p>Attention, connectivity, input, resources and available capabilities shape the experience.</p>${prompt('Would a large iPad screen remove the challenges Mali faces?')}<p class="small">Working course definition: software designed for portable, personal computing and its changing use conditions.</p>`},
{id:'interruption',title:"A call arrives. Mali returns to an empty route.",time:5,chapter:"2 / The journey is interrupted",body:`<p>Mali returns from a call. Her selected route has vanished. What should survive?</p>`+steps(['Open app','Interruption','Background','Network changes','Return'])+cards([['Preserve','Keep the selected route and meaningful work.'],['Communicate','Identify old information as old.'],['Conserve','Avoid unnecessary battery, data and processing use.']])+`<p class="small">The operating system controls execution opportunities. This is a possible user journey, not a formal lifecycle state diagram.</p>`,source:link('Apple · Scene',apple+'documentation/swiftui/scene')},
{id:'inclusive',title:"Her route returns. She still cannot save it.",time:8,chapter:"2 / Try another repair",body:`<div class="split"><div><p class="lead">Her route is back, but Save requires a swipe. Mali still holds her umbrella.</p><p>Try a visible Save button. Would it also work with large text, a keyboard or a screen reader?</p></div><div class="card"><h3>Keep essential actions available</h3><ul><li>Use familiar, labeled controls.</li><li>Allow text and layout to adapt.</li><li>Offer alternatives to custom gestures.</li><li>Use more than color to convey meaning.</li></ul></div></div>${prompt('“Swipe the bus card to save it.” What other way should the app provide?')}`,source:access+' · '+link('Apple · Gestures',apple+'design/human-interface-guidelines/gestures')},
{id:'classify',title:"Theory: continuity and inclusive interaction",time:9,chapter:"2 / Name what happened",body:`<p>Choose a driver, then explain your “because.” More than one can fit.</p><div class="matching">${['Show “Updated 2 min ago”','Preserve the selected route','Let large text grow without clipping','Request location after “Find nearest stop”'].map((s,i)=>`<label>${s}<select aria-label="Driver for ${esc(s)}"><option value="">Choose a driver</option>${['Connectivity','Lifecycle / attention','Accessibility','Privacy / context','Resources'].map(x=>`<option>${x}</option>`).join('')}</select></label>`).join('')}</div><button type="button" data-reset>Reset</button>${reveal('Discuss the causal links','Freshness matters when connections fail; returning users need continuity; flexible text supports accessibility; a clear moment of need helps explain permission. Defend a different match if you can show the link.')}`},
{id:'permission',title:"“Find my stop” asks for too much.",time:7,chapter:"3 / Mali says no",body:`<div class="split"><div class="card"><h3>At launch</h3>${steps(['Location?','Notifications?','Contacts?'])}<p>Mali refuses: she only wanted a stop.</p></div><div class="card mint"><h3>At the moment of need</h3>${steps(['Find nearest stop','Explain the purpose','Request location','Handle allow or deny'])}</div></div>${prompt('Mali taps Don’t Allow. Propose a way forward, then compare: let her choose a stop manually.')}`,source:privacy},
{id:'capabilities',title:"Theory: capability comes with responsibility",time:5,chapter:"3 / Name what happened",body:cards([['Always nearby','Useful at the point of need.<br><strong>Design for:</strong> brief, interrupted attention.'],['Aware of context','Location, motion, camera and microphone.<br><strong>Account for:</strong> accuracy, access and battery.'],['Personal','Continuity and personalization.<br><strong>Protect:</strong> identity and sensitive data.']])+prompt('Does finding the nearest stop justify tracking someone all day?'),source:privacy},
{id:'tradeoffs',title:"Theory: quality means justified tradeoffs",time:4,chapter:"3 / Explain the repair",body:`<p class="lead">Refreshing more often can improve freshness—and use more battery and data.</p>${cards([['Useful + resilient','Solve the urgent task, including interruption and uncertainty.'],['Efficient + inclusive','Respect resources and attention; support varied abilities and contexts.'],['Trustworthy','Collect justified data and make its use visible and controllable.']])}${prompt('What refresh behavior would you choose while the app is closed? What fact is missing?')}`},
{id:'checkpoint',title:"Mali can choose. Explain why.",time:3,chapter:"Act I / Retrieve",kind:'statement',body:`<p class="statement">Mobile software differs because <em>______</em> changes;<br>therefore the app should <em>______</em>.</p><p>Use context, connection, attention, input, permission or resources.</p>`},
{id:'swift-trace',title:"The team prints an arrival. Where is the app?",time:5,chapter:"4 / Behind the screen",body:`<div class="split"><div>${code('let stop = "North Gate"\nlet minutes = 4\nprint("\\(stop): \\(minutes) min")')}<p>Predict the console output.</p><label for="minutes">Then change the supplied value: <output id="minutes-value">4</output> minutes</label><input id="minutes" type="range" min="1" max="10" value="4"><button type="button" data-reset>Reset</button></div><div><p class="eyebrow">CONSOLE PREDICTION</p><details id="trace"><summary>Reveal output</summary><pre id="trace-output" aria-live="polite">North Gate: 4 min</pre></details><p class="small">A JavaScript model of this specific expression, not a Swift compiler.</p><p>Who defines <code>let</code>? Who reports syntax errors? Who draws a <code>Text</code> view?</p></div></div>`,source:swift},
{id:'view',title:"Now give Mali something she can see.",time:5,chapter:"4 / Try a screen",body:`<div class="split"><div>${code('import SwiftUI\n\nstruct ShuttleStatusView: View {\n    var body: some View {\n        VStack {\n            Text("North Gate Shuttle")\n            Text("Updated 2 min ago")\n        }\n    }\n}')}</div><div><p class="lead">Sketch the two visible elements.</p><p>Which word describes their arrangement?</p>${reveal('Reveal the composition','<div class="mini-screen"><strong>North Gate Shuttle</strong><span>Updated 2 min ago</span></div><p>VStack places its child views vertically. Text supplies visible content.</p>')}<p class="small">SwiftUI excerpt. Full source is in the practice download. Compilation pending course-device verification.</p></div></div>`,source:link('Apple · Hello, SwiftUI',apple+'tutorials/develop-in-swift/hello-swiftui')},
{id:'stack',title:"Theory: from source to a running app",time:5,chapter:"4 / Name the roles",body:`<div class="split"><div class="card"><h3>Build time · on the Mac</h3>${steps(['Swift source + assets','Xcode invokes compiler + SDK','An app build'])}<p class="small">Swift is a language. Xcode is an IDE. An SDK supplies platform interfaces and build resources.</p></div><div class="card mint"><h3>Run time · device or simulator</h3>${steps(['Your app + framework APIs','iOS / iPadOS services','Display · storage · network · sensors'])}<p class="small">The OS mediates protected resources. The simulator supports testing but cannot replace every hardware check.</p></div></div><p class="small">This responsibility map separates development tools from runtime layers.</p>`,source:tools},
{id:'framework',title:"Theory: a framework owns part of the work",time:4,chapter:"4 / Name the structure",body:cards([['Language','A way to express values, logic and types.'],['Library','Reusable code your code calls.'],['Framework','Structure, conventions and runtime behavior that call your code at defined points.']])+`<p class="lead">Swift is the language. SwiftUI supplies a framework for interfaces.</p><p class="small">Next week: how events and state updates move through that framework.</p>`,source:ui},
{id:'forces',title:"One repaired screen becomes many.",time:3,chapter:"5 / The team cannot keep up",body:`<p>The team must handle current, stale and unavailable arrivals on different screens.</p>`+cards([['More platforms','New capabilities, form factors and input methods.'],['More states','Live data, interruptions and asynchronous events.'],['More responsibility','Accessibility, privacy and maintainable software.']])+prompt('Which problems remain even if phones become infinitely fast?')},
{id:'declarative',title:"The warning changes. The Retry button does not.",time:4,chapter:"5 / Compare two repairs",body:`<div class="split"><div class="card"><h3>Repair A · Update each part</h3><p>The text changes, but someone forgets Retry. Which steps must stay consistent?</p>${steps(['Find the label','Change its text','Change its color','Show Retry'])}</div><div class="card mint"><h3>Repair B · Describe the result</h3><p>What should appear for this state?</p><p class="big-code">stale data<br>↓<br>timestamp + warning + Retry</p></div></div><p class="small">Conceptual pseudocode. Both approaches still execute instructions.</p>`,source:link('Apple · SwiftUI Pathway',apple+'swiftui/get-started/')},
{id:'contract',title:"Theory: imperative and declarative UI",time:4,chapter:"5 / Name the abstraction",body:`<p><strong>Imperative:</strong> specify update steps. <strong>Declarative:</strong> describe the UI for its state.</p><table><thead><tr><th>You describe</th><th>Framework and system coordinate</th></tr></thead><tbody><tr><td>Hierarchy and content</td><td>Rendering the interface</td></tr><tr><td>State and its visible result</td><td>Updating affected views</td></tr><tr><td>Layout intent</td><td>Layout and drawing details</td></tr><tr><td>Responses to events</td><td>Delivering input and lifecycle events</td></tr></tbody></table><p class="takeaway">You still own the data model, app rules and user experience.</p>`,source:ui},
{id:'evolution',title:"Theory: the problems behind the milestones",time:6,chapter:"5 / Connect to history",body:`<ol class="timeline"><li><strong>2008 · iPhone SDK + App Store</strong><span>Official device APIs, tools and a distribution channel.</span></li><li><strong>UIKit · Event-driven interfaces</strong><span>Compose platform views; coordinate their updates.</span></li><li><strong>2014 / 2015 · Swift</strong><span>A modern type-safe language, then open-source development.</span></li><li><strong>2019 · SwiftUI</strong><span>Describe UI declaratively; compose views and use previews.</span></li><li><strong>Coexistence</strong><span>SwiftUI and UIKit can be adopted together.</span></li></ol><p class="small">A selective Apple timeline. These are language, framework and ecosystem milestones—not interchangeable categories.</p>`,source:swift+' · '+ui+' · '+link('Apple · 2008 SDK context','https://www.apple.com/ie/newsroom/2008/05/13Apple-Executives-to-Showcase-Mac-OS-X-Leopard-and-OS-X-iPhone-Development-Platforms-at-WWDC-2008-Keynote/')+' · '+link('SwiftUI introduction · 2019',apple+'videos/play/wwdc2019/204/')},
{id:'decision',title:"The campus wants it. Who gets the first version?",time:5,chapter:"6 / The audience grows",body:`<p>The same shuttle service has three possible first audiences. Choose one with a partner.</p>`+cards([['A · Campus visitors','Scan a QR code at a stop. No account or installation. Read arrivals.'],['B · Shuttle operations','Managed university iPhones. Location during shifts. Weak connectivity.'],['C · Enrolled students','iOS + Android. A small web-skilled team. Saved stops and notifications.']])+prompt('How would people open your first version? Explain a benefit and a possible obstacle.')+`<p class="small">Use plain language first. We will name the delivery approaches after comparing your choices. Never require a driver to interact while driving.</p>`},
{id:'mobile-poll',title:"A link, an icon, a counter, a watch.",time:6,chapter:"6 / Test the boundary",body:`<fieldset class="poll"><legend>Select every case you would include.</legend>${['A responsive university website in Safari','An installed Progressive Web App','An iPad checkout app fixed to a counter','A watch app recording a run without a phone'].map((x,i)=>`<label><input type="checkbox" name="mobile" value="${i}"> ${x}</label>`).join('')}</fieldset>${prompt('What rule explains your choices?')}<button type="button" data-reset>Reset choices</button>${reveal('Compare definitions','Device category, delivery model and usage context are different dimensions. An icon does not prove an app uses a native framework. Explain which dimension your definition emphasizes.')}`,source:web},
{id:'approaches',title:"Theory: native, cross-platform and mobile web",time:4,chapter:"6 / Name the choices",body:cards([['Native','Platform SDKs and frameworks.<br><strong>Gain:</strong> direct platform integration.<br><strong>Consider:</strong> platform-specific expertise.'],['Cross-platform','Share substantial code through a framework.<br><strong>Gain:</strong> shared implementation.<br><strong>Consider:</strong> platform adaptations and dependencies.'],['Mobile web / PWA','Browser delivery with progressive capabilities.<br><strong>Gain:</strong> reach through a link.<br><strong>Consider:</strong> browser and API support.']])+`<p class="small">These categories overlap: SwiftUI spans Apple platforms; cross-platform tools can render native components. Shared code still requires platform testing.</p>`,source:ui+' · '+react+' · '+web},
{id:'criteria',title:"Theory: choose from constraints",time:5,chapter:"6 / Defend the ending",body:`<div class="criteria">${[['Reach','Which devices and platforms?'],['Capabilities','Which integrations are essential?'],['Experience','Which conventions and access needs?'],['Reliability','What survives weak connectivity?'],['Team + time','Who can build and maintain it?'],['Distribution','A link, managed device or app store?']].map(([a,b])=>`<div><h3>${a}</h3><p>${b}</p></div>`).join('')}</div>${prompt('Return to your shuttle audience: give two criteria, one risk and one fact to verify. Would you change your first proposal?')}`},
{id:'takeaways',title:"Back at the stop: what did we learn?",time:4,chapter:"Epilogue / Exit ticket",body:`<div class="split"><div><ol><li><strong>Context creates requirements.</strong><br>Classify the condition before proposing a feature.</li><li><strong>Frameworks redistribute work.</strong><br>Explain what a new abstraction helps manage.</li><li><strong>Tools have distinct roles.</strong><br>Swift, SwiftUI and Xcode are different things.</li><li><strong>Choices need criteria.</strong><br>Justify the approach and name uncertainty.</li></ol></div><div class="card mint"><h3>Exit ticket</h3><p>1. One mobile condition → one requirement.</p><p>2. One milestone → the problem it addressed.</p><p>3. Swift vs SwiftUI, in one sentence.</p><p class="small">Discuss or record for your own review. This page does not collect responses.</p></div></div><p class="small">Next lab: create → edit → run → introduce an error → repair.<br>Our course path: Swift + SwiftUI, using Xcode on Mac or Swift Playgrounds on iPad.</p><p class="download-links"><a href="../../downloads/week-01-practice.zip" download>Download practice source</a> · <a href="../../downloads/week-01-offline.zip" download>Download offline lesson</a></p>`,source:ui},
];
